<main>
	<h1>{'Northridge Devs'.toUpperCase()}</h1>
	<figure>
		<img src="/northridge-dev.webp" alt="Northridge Devs Banner" />
		<figcaption>Knights coding. Image generated by a diffusion model (Adobe Firefly)</figcaption>
	</figure>
</main>

<style>
	main {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	img {
		width: auto;
	}

	h1 {
		font-weight: 600;
		font-size: 3.5rem;
	}
</style>
